/**
 * Autonomous generator: converts the curated ability-overrides source JSON into
 * type-safe UI data modules consumed by unit pages and the unit browser.
 *
 * Source of truth: src/data/ability-overrides.source.json (committed).
 * Outputs:
 *   - src/lib/ability-types.ts   (the Ability interface)
 *   - src/lib/unit-abilities.ts  (curated ability map + accessors)
 *
 * Only abilities that have a non-empty `description` are emitted — undescribed
 * entries are considered not-yet-curated and are skipped.
 *
 * Run: `pnpm gen:abilities` (optionally pass a custom source path as argv[2]).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(scriptDir, '..');

interface AbilityOverride {
  title?: string;
  icon?: string;
  description?: string;
  kind?: 'active' | 'passive';
  actionPoints?: number;
  cooldown?: number;
  notes?: string;
}

interface AbilitySource {
  generatedAt?: string;
  storageKey?: string;
  entries: Record<string, AbilityOverride>;
}

interface CuratedAbility {
  id: number;
  title: string;
  icon?: string;
  description: string;
  kind: 'active' | 'passive';
  actionPoints: number;
  cooldown: number;
  notes?: string;
}

const typeDef = `export interface Ability {
  id: number;
  title: string;
  icon?: string;
  description: string;
  kind: 'active' | 'passive';
  actionPoints: number;
  cooldown: number;
  /** Player field-test note (not in game data). Curated locally via the editor. */
  notes?: string;
}
`;

function entry(a: CuratedAbility): string {
  const iconLine = a.icon ? `\n    icon: ${JSON.stringify(a.icon)},` : '';
  const notesLine = a.notes ? `\n    notes: ${JSON.stringify(a.notes)},` : '';
  return `  ${a.id}: {
    id: ${a.id},
    title: ${JSON.stringify(a.title)},${iconLine}
    description: ${JSON.stringify(a.description)},
    kind: ${JSON.stringify(a.kind)},
    actionPoints: ${a.actionPoints},
    cooldown: ${a.cooldown},${notesLine}
  },`;
}

/**
 * Reads the curated ability source JSON and (re)writes the type-safe UI data
 * modules. Exported so the dev editor middleware can regenerate on save.
 * Returns a small summary for logging.
 */
export function generateAbilityUi(sourcePath?: string): {
  total: number;
  active: number;
  passive: number;
} {
  const resolvedSource =
    sourcePath ?? path.join(projectRoot, 'src', 'data', 'ability-overrides.source.json');

  const data = JSON.parse(readFileSync(resolvedSource, 'utf8')) as AbilitySource;

  const curated: CuratedAbility[] = Object.entries(data.entries)
    .filter(([, a]) => typeof a.description === 'string' && a.description.trim().length > 0)
    .map(([id, a]) => ({
      id: Number(id),
      title: a.title ?? 'Unknown',
      ...(a.icon ? { icon: a.icon } : {}),
      description: a.description ?? '',
      kind: a.kind ?? 'active',
      actionPoints: a.actionPoints ?? 0,
      cooldown: a.cooldown ?? 0,
      ...(a.notes ? { notes: a.notes } : {}),
    }))
    .sort((x, y) => x.id - y.id);

  const dataModule = `import type { Ability } from './ability-types';

/**
 * Curated ability database with full descriptions.
 * AUTO-GENERATED by scripts/generate-ability-ui.ts from
 * src/data/ability-overrides.source.json — do not edit by hand.
 * Source timestamp: ${data.generatedAt ?? 'unknown'}
 */
export const abilities: Record<number, Ability> = {
${curated.map(entry).join('\n')}
};

export function getAbility(id: number): Ability | undefined {
  return abilities[id];
}

export function getAbilities(ids: number[]): Ability[] {
  return ids.map((id) => abilities[id]).filter((a): a is Ability => a !== undefined);
}
`;

  const typesOut = path.join(projectRoot, 'src', 'lib', 'ability-types.ts');
  const dataOut = path.join(projectRoot, 'src', 'lib', 'unit-abilities.ts');

  writeFileSync(typesOut, typeDef, 'utf8');
  writeFileSync(dataOut, dataModule, 'utf8');

  const active = curated.filter((a) => a.kind === 'active').length;
  return { total: curated.length, active, passive: curated.length - active };
}

// CLI entry: run directly via `pnpm gen:abilities [sourcePath]`.
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const sourceArg = process.argv[2];
  console.log(
    `Reading curated ability data from: ${sourceArg ?? 'src/data/ability-overrides.source.json'}`,
  );
  const summary = generateAbilityUi(sourceArg);
  console.log(`Found ${summary.total} curated abilities with descriptions.`);
  console.log('Generated: src/lib/ability-types.ts');
  console.log('Generated: src/lib/unit-abilities.ts');
  console.log(
    `\nSummary: ${summary.total} abilities (${summary.active} active, ${summary.passive} passive).`,
  );
}
