Name: Old Cemetery
Description: This cemetery is far from Yanidor, and that's why it is not used anymore. There's a new one, closer to the village. All the better for me to safely conduct business.
ShortQuestDescr: Gather some cemetery earth

