Name: 방적공의 이즈바
Description: 또 이 저주받은 이즈바군... 할아버지의 도움을 기다릴 시간은 없어. 내 혼자 힘으로 책을 되찾을 거야!
ShortQuestDescr: 검은 책 되찾기
LongQuestDescr: 방적공이 당신의 마법 필사본을 가져갔습니다! 당신은 온 구베르니아에서 가장 귀중한 유물을 찾아 방적공의 이즈바로 향했습니다.

