Name: Друзья-солевары
AbilityType: MERMAID_FRIENDS
TargetType: SELF
AbilitySpellType: SUMMON
Sprite: MERMAID_FRIENDS
GoldCost: 3
Effects:
- EffectType: SUMMON
  MinValue: 1
  MaxValue: 1
  SummonEffectData:
    UnitTypes:
    - Drowner
  VisualEffect:
    VisualEffectType: SIMPLE_ATTACK
    ReadyTrigger: Spell
    SpellTrigger: Spell
    MissTrigger: Miss
    SkipReady: true

