Name: Ветер-Лука+
AbilityType: WIND_LUKA_UP
TargetType: ENEMY
Description: "{MinValue} урона \nОткрывает случайную страницу"
Sprite: WindLukaAbility
GoldCost: 7
Effects:
- MinValue: 3
  MaxValue: 3
  VisualEffect:
    VisualEffectType: KILA
    ReadyTrigger: Word
    SpellTrigger: AttackSpell
    MissTrigger: AttackSpell
    WrapUpTime: 2
- EffectType: PAGE_RANDOM

