DayToTitle:
  1:
    Date: 第一章
    Title: バーニャからの連れ去り
  7:
    Date: 第二章
    Title: ヴォジャノーイを探して
  14:
    Date: 第三章
    Title: コルドゥンは結婚式を呪う
  21:
    Date: 第四章
    Title: 森を歩くレーシィ
  26:
    Date: 第五章
    Title: 咲き誇る羊歯
  32:
    Date: 第六章
    Title: コルドゥンの死
  35:
    Date: 第七章
    Title: 罪びとは地獄に苦しむ

