Id: Map3
MinTextQuestGoldReward: 50
MaxTextQuestGoldReward: 100
SatanItemRewardsCount: 3
SatanHpReward: 10
SatanSpReward: 3
IdToBlueprint:
  Fight1:
    Id: Fight1
    Sprite: RGFight
    NodeType: Fight
    AbilityDropType: Regular
    Scenes:
      - HellTarPits
      - Hell
      - HellBarracks
      - HellTarPits
      - HellBridge
      - HellTelega
    Enemies:
      - - DemonHealer
      - - Menqw
      - - DemonBrander
  Fight2:
    Id: Fight2
    Sprite: RGFight
    NodeType: Fight
    AbilityDropType: Regular
    Scenes:
      - HellTarPits
      - Hell
      - HellBarracks
      - HellTarPits
      - HellBridge
      - HellTelega
    Enemies:
      - - DemonButcher
        - Demon
      - - DemonFire
        - Demon
      - - WoodenAngel
        - Demon
      - - DemonSoldierLeader
        - Demon
      - - WolfHalf
        - Demon
      - - DemonFierce
        - Demon
        - Demon
      - - SwampFire
        - Demon
        - Demon
      - - Chud3
        - Demon
        - Demon
      - - DemonSpiked
        - Demon
        - Demon
      - - ForestDemonRoots
        - Demon
        - Demon
      - - DemonButcher
        - Demon
        - Demon
      - - DemonFierce
        - DemonSpiked
      - - SwampFire
        - DemonSpiked
      - - Chud3
        - DemonSpiked
      - - ForestDemonRoots
        - DemonSpiked
      - - DemonButcher
        - DemonSpiked
  Fight3:
    Id: Fight3
    Sprite: RGFight
    NodeType: Fight
    AbilityDropType: Regular
    Scenes:
      - HellTarPits
      - Hell
      - HellBarracks
      - HellTarPits
      - HellBridge
      - HellTelega
    Enemies:
      - - DemonButcher
        - Demon
      - - DemonFire
        - Demon
      - - WoodenAngel
        - Demon
      - - DemonSoldierLeader
        - Demon
      - - WolfHalf
        - Demon
      - - DemonFierce
        - Demon
        - Demon
      - - SwampFire
        - Demon
        - Demon
      - - Chud3
        - Demon
        - Demon
      - - DemonSpiked
        - Demon
        - Demon
      - - ForestDemonRoots
        - Demon
        - Demon
      - - DemonButcher
        - Demon
        - Demon
      - - DemonFierce
        - DemonSpiked
      - - SwampFire
        - DemonSpiked
      - - Chud3
        - DemonSpiked
      - - ForestDemonRoots
        - DemonSpiked
      - - DemonButcher
        - DemonSpiked
  EliteFight:
    Name: Elite Enemy
    Id: EliteFight
    Sprite: RGFightHard
    NodeType: Fight
    IsArtefactReward: true
    ScaleCoeff: 1.2
    SpReward: 1
    AbilityDropType: RegularElite
    Scenes:
      - HellTarPits
      - Hell
      - HellBarracks
      - HellTarPits
      - HellBridge
      - HellTelega
    Enemies:
      - - DemonPimped
      - - Chud1
        - Demon
      - - DemonHealer
        - Demon
      - - Menqw
        - Demon
      - - DemonBrander
        - Demon
      - - DemonPimped
        - Demon
      - - DemonFire
        - Demon
        - Demon
      - - WoodenAngel
        - Demon
        - Demon
      - - DemonSoldierLeader
        - Demon
        - Demon
      - - WolfHalf
        - Demon
        - Demon
      - - Chud1
        - Demon
        - Demon
      - - DemonHealer
        - Demon
        - Demon
      - - Menqw
        - Demon
        - Demon
      - - DemonBrander
        - Demon
        - Demon
      - - DemonFire
        - DemonSpiked
      - - WoodenAngel
        - DemonSpiked
      - - DemonSoldierLeader
        - DemonSpiked
      - - WolfHalf
        - DemonSpiked
      - - Chud1
        - DemonSpiked
      - - DemonHealer
        - DemonSpiked
      - - Menqw
        - DemonSpiked
      - - DemonBrander
        - DemonSpiked
      - - DemonFierce
        - Menqw
      - - SwampFire
        - Menqw
      - - Chud3
        - Menqw
      - - DemonSpiked
        - Menqw
      - - ForestDemonRoots
        - Menqw
      - - DemonButcher
        - Menqw
  RestSite:
    Name: Rest Site
    Id: RestSite
    Sprite: RGCamp
    NodeType: RestSite
    DialogueSystemNames:
      - TextQuest/Util/Rest
    Scenes:
      - HellTarPits
  Loot:
    Name: Loot
    Id: Loot
    Sprite: RGLoot
    NodeType: Loot
    Scenes:
      - Hell
    Items:
      - RoyalEyes
      - AdamHead
      - CryingHerb
      - BreakHerb
      - Ladan
      - OdolenHerb
      - Sota
      - CuckooTears
      - DreamHerb
      - Suporijki
      - SaintWater
      - Dagil
      - Borvyak
      - LadanTrava
      - ShutemTrava
      - BessmertTrava
    SpecialItems:
      - Ribbon
      - HeadSnake
      - Gusli
      - DevilBannerRoguelike
      - Morteshka
      - BurstingBone
      - ChurchKnife
      - ProkopiyStaff
      - SickCandles
      - BearPaw
      - BlueBoots
      - BrotherHoof
      - ArmyWorm
      - Darochka
      - Goddess
      - PikeTooth
      - DeadManSpindle
      - AlchemyBottle
      - ChristEgg
      - SinnerEye
      - Mooseman
      - Superik
      - Varakul
      - BurntStick
      - CoffinNails
      - Bag3
      - SewnIcon
      - HerbAmulet
      - Kiryan
      - HeruvimUnknown
      - Volhid
      - HeadDead
      - HeadWorm
      - SpoonWood
      - SecretPage
  BigLoot:
    Name: Big Loot
    Id: BigLoot
    Sprite: RGLootBig
    NodeType: Loot
    ScaleCoeff: 1.2
    ArtefactCount: 1
    Scenes:
      - Hell
    Items:
      - Week1Axe
    SpecialItems:
      - Ribbon
      - HeadSnake
      - HeadDead
      - Gusli
      - Morteshka
      - HeadWorm
      - SpoonWood
      - DevilBannerRoguelike
      - KonekGorbunok
      - BurstingBone
      - ChurchKnife
      - ProkopiyStaff
      - SickCandles
      - BearPaw
      - BlueBoots
      - ArmyWorm
      - Darochka
      - Goddess
      - BrotherHoof
      - PikeTooth
      - DeadManSpindle
      - AlchemyBottle
      - ChristEgg
      - SinnerEye
      - Mooseman
      - Superik
      - Varakul
      - BurntStick
      - CoffinNails
      - Bag3
      - SewnIcon
      - HerbAmulet
      - Kiryan
      - HeruvimUnknown
      - Volhid
      - SecretPage
  Merchant:
    Name: Merchant
    Id: Merchant
    Sprite: RGMerchant
    NodeType: Merchant
    Scenes:
      - FairHell
    DialogueSystemNames:
      - TextQuest/Merchant/Fair
    Merchants:
      - DemonHerbalist
      - DemonPeddler
      - BookKeeper3
  Satan:
    Name: Satan
    MusicOverride: event:/Music/BattleSatan
    NoExplorationMusic: true
    Id: Satan
    Sprite: RGSatan
    NodeType: Fight
    IsBoss: true
    IsFinalBoss: true
    ScaleCoeff: 2.5
    EpicParticles: true
    SpReward: 5
    AbilityDropType: Boss
    Scenes:
      - HellThrone
    Enemies:
      - - Satan1Roguelike
  BossGeneric:
    Name: Satan
    MusicOverride: event:/Music/BattleSatan
    NoExplorationMusic: true
    Id: Satan
    Sprite: RGSatan
    NodeType: Fight
    IsBoss: true
    IsFinalBoss: true
    ScaleCoeff: 2.5
    EpicParticles: true
    SpReward: 5
    AbilityDropType: Boss
    Scenes:
      - HellThrone
    Enemies:
      - - Porcha
      - - Leshak
      - - FilimonDemon
      - - SnakeSorcerer
  Unknown:
    Name: Unknown
    Id: Unknown
    Sprite: RGUnknown
    NodeType: Unknown
    UnknownBlueprints:
      - Merchant
      - Fight2
      - Loot
      - Loot
      - Loot
      - BigLoot
      - BigLoot
      - Booker
      - Fight2
      - Fight2
  Booker:
    Name: Booker
    Id: Booker
    Sprite: RGBooker
    NodeType: Merchant
    Scenes:
      - HellTelega
    Merchants:
      - BookKeeper3
  Herbalist:
    Name: Herbalist
    Id: Herbalist
    Sprite: RGHerbalist
    NodeType: Merchant
    Scenes:
      - HellTelega
    Merchants:
      - DemonHerbalist
  Ally:
    Name: Ally
    Id: Ally
    Sprite: RGFool
    NodeType: Ally
    DialogueSystemNames:
      - TextQuest/Util/Ally
    Scenes:
      - Hell
    Allies:
      - DedEgorLoyal
      - KarnyshLoyal
      - NikolayLoyal
      - ProshkaLoyal
      - WhiteHeadLoyal
#  Text:
#    Name: Text
#    Id: Text
#    Sprite: RGText
#    NodeType: Text
#    Scenes:
#      - Forest
#      - CrossroadsExploration
#      - Forest_3
#      - Marshes2
#      - Forest_Bridge_2
#      - Road
#      - Backwater
#      - Forest_3
#      - Cemetery
#      - Forest_5
#    DialogueSystemNames:
#      - TextQuest/Herb/Break
#      - TextQuest/Herb/OdolenHerb
#      - TextQuest/Herb/KolukaHerb
#      - TextQuest/Herb/PrikryshHerb
#      - TextQuest/Herb/TirlichHerb
#      - TextQuest/Herb/CryingHerb
#      - TextQuest/Herb/Adam
#      - TextQuest/Artefact/Poker
#      - TextQuest/Artefact/WhiteHead
#      - TextQuest/Artefact/DeadManCross
#      - TextQuest/Artefact/ArmyWorm
#      - TextQuest/Artefact/ThunderArrow
GridWidth: 7
PreBossNodesMin: 2
PreBossNodesMax: 3
StartingNodesMin: 3
StartingNodesMax: 5
DistanceFromPreviousLayerMin: 9
DistanceFromPreviousLayerMax: 10
Layers:
  - DefaultBlueprintId: Fight1
    NodesApartDistance: 5.4
    RandomizePosition: 0
    RandomizeNodes: 0
  - DefaultBlueprintId: Fight1
    PossibleBlueprintsIds:
      - Fight1
      - Fight1
      - Fight1
      - Loot
      - Loot
      - Loot
      - Loot
      - Loot
      - Loot
      - Unknown
      - Loot
    NodesApartDistance: 5.4
    RandomizePosition: 0.55
    RandomizeNodes: 1
  - DefaultBlueprintId: Fight2
    PossibleBlueprintsIds:
      - Fight2
      - Fight2
      - Fight2
      - Fight2
      - Fight2
      - Fight2
      - Fight2
      - Fight2
      - Unknown
      - Unknown
      - EliteFight
      - EliteFight
      - Fight2
      - Unknown
      - Fight2
    NodesApartDistance: 5.4
    RandomizePosition: 0.55
    RandomizeNodes: 0.75
  - DefaultBlueprintId: Fight2
    PossibleBlueprintsIds:
      - Fight2
      - Fight2
      - Fight2
      - Fight2
      - Fight2
      - EliteFight
      - EliteFight
      - EliteFight
      - Unknown
      - Fight2
      - Fight2
      - Unknown
    NodesApartDistance: 5.4
    RandomizePosition: 0.55
    RandomizeNodes: 1
  - DefaultBlueprintId: Fight2
    PossibleBlueprintsIds:
      - Fight2
      - Fight2
      - Fight2
      - Fight2
      - Fight2
      - Unknown
      - Fight2
      - Fight2
      - Unknown
    NodesApartDistance: 5.4
    RandomizePosition: 0.55
    RandomizeNodes: 1
  - DefaultBlueprintId: Fight3
    PossibleBlueprintsIds:
      - Loot
      - Loot
      - Merchant
      - Merchant
      - Merchant
      - Merchant
      - Merchant
      - Merchant
      - Merchant
      - Merchant
      - RestSite
      - Merchant
      - Merchant
      - Ally
      - Ally
    NodesApartDistance: 5.4
    RandomizePosition: 0.55
    RandomizeNodes: 1
  - DefaultBlueprintId: Fight3
    PossibleBlueprintsIds:
      - Fight3
      - Fight3
      - Fight3
      - Fight3
      - EliteFight
      - EliteFight
      - EliteFight
      - EliteFight
      - Unknown
      - Loot
      - BigLoot
      - Unknown
    NodesApartDistance: 5.4
    RandomizePosition: 0.55
    RandomizeNodes: 1
  - DefaultBlueprintId: Fight3
    PossibleBlueprintsIds:
      - Loot
      - Loot
      - Loot
      - Herbalist
      - Booker
      - Loot
      - Loot
      - Loot
      - Unknown
      - Loot
      - BigLoot
      - Unknown
    NodesApartDistance: 5.4
    RandomizePosition: 0.55
    RandomizeNodes: 1
  - DefaultBlueprintId: Fight3
    PossibleBlueprintsIds:
      - Fight3
      - Fight3
      - Fight3
      - Fight3
      - EliteFight
      - EliteFight
      - EliteFight
      - EliteFight
      - Unknown
      - Fight3
      - Fight3
      - Unknown
    NodesApartDistance: 5.4
    RandomizePosition: 0.55
    RandomizeNodes: 1
  - DefaultBlueprintId: RestSite
    NodesApartDistance: 5
    RandomizePosition: 0.55
    RandomizeNodes: 0
  - DefaultBlueprintId: BossGeneric
    NodesApartDistance: 5
    RandomizePosition: 0
    RandomizeNodes: 1
    PossibleBlueprintsIds:
      - BossGeneric
BattleWinItemRewards:
  - Item: RoyalEyes
    Quantity: 1
  - Item: Ladan
    Quantity: 1
  - Item: Sivulist
    Quantity: 1
  - Item: SnakeHerb
    Quantity: 1
  - Item: Dedovniki
    Quantity: 1
  - Item: Perekop
    Quantity: 1
  - Item: DungLips
    Quantity: 1
  - Item: Dagil
    Quantity: 1
  - Item: ArhilinHerb
    Quantity: 1
  - Item: BreakHerb
    Quantity: 2
  - Item: CryingHerb
    Quantity: 2
  - Item: KolukaHerb
    Quantity: 1
  - Item: OdolenHerb
    Quantity: 2
  - Item: PetrovHerb
    Quantity: 1
  - Item: PrikryshHerb
    Quantity: 1
  - Item: TirlichHerb
    Quantity: 2
  - Item: IndiviaHerb
    Quantity: 2
  - Item: Braga
    Quantity: 2
  - Item: Sota
    Quantity: 2
  - Item: CuckooTears
    Quantity: 2
  - Item: WormwoodHerb
    Quantity: 2
  - Item: Bolotvik
    Quantity: 2
  - Item: Priputnik
    Quantity: 2
  - Item: DreamHerb
    Quantity: 2
  - Item: Suporijki
    Quantity: 2
  - Item: Bogomor
    Quantity: 2
  - Item: Solodelik
    Quantity: 2
  - Item: RottenMushroom
    Quantity: 2
  - Item: DogMushroom
    Quantity: 2
  - Item: EremaMushroom
    Quantity: 2
  - Item: Borvyak
    Quantity: 1
  - Item: LadanTrava
    Quantity: 2
  - Item: ShutemTrava
    Quantity: 1
  - Item: WhiteHeadTrava
    Quantity: 1
  - Item: SecretLeaveTrava
    Quantity: 1
  - Item: BessmertTrava
    Quantity: 1
BattleWinBossItemRewards:
  - Item: BookBlack
    Quantity: 1
  - Item: DevilBannerRoguelike
    Quantity: 1
  - Item: DeadWear
    Quantity: 1
  - Item: SinnerRib
    Quantity: 1
  - Item: DuckEarrings
    Quantity: 1
  - Item: Superik
    Quantity: 1
  - Item: SharpStuff
    Quantity: 1
  - Item: Bag3
    Quantity: 1
  - Item: Kadilnitsa
    Quantity: 1
  - Item: BookDead
    Quantity: 1
  - Item: BookMagic
    Quantity: 1
  - Item: SewnIcon
    Quantity: 1
  - Item: HerbAmulet
    Quantity: 1
  - Item: LifeParaskeva
    Quantity: 1
  - Item: BookPsaltir
    Quantity: 1
  - Item: ArmyWorm
    Quantity: 1
  - Item: BrotherHoof
    Quantity: 1
  - Item: BlueBoots
    Quantity: 1
  - Item: Mooseman
    Quantity: 1
  - Item: Goddess
    Quantity: 1
  - Item: ProkopiyStaff
    Quantity: 1
  - Item: ChurchKnife
    Quantity: 1
  - Item: Darochka
    Quantity: 1
  - Item: AlchemyBottle
    Quantity: 1
  - Item: ChristEgg
    Quantity: 1
  - Item: SinnerEye
    Quantity: 1
MerchantAbilities:
  - LOMOTA
  - CHAINS_OF_FIRE
  - KAIN
  - KOSTOLOMISHE
  - CHEMER
  - UBEITSA
  - SKORCHEN
  - OGNEVITSA
  - TOMASHIHA
  - WIND_FIERCE
  - ANTIPKA
  - HOHOR
  - KILA
  - CROSS2
  - FAITHFUL_HOPE
  - IROD_BONES
  - DEAD_MAN
AbilityDropTypeToList:
  Regular:
    - UBEITSA
    - SKORCHEN
    - KORKUSHA
    - OGNEVITSA
    - TOMASHIHA
    - WIND_FIERCE
    - ANTIPKA
    - HOHOR
    - KILA
    - CROSS2
    - KNIFE
    - FAITHFUL_HOPE
    - IROD_BONES
    - DEAD_MAN
  RegularElite:
    - LOMOTA
    - CHAINS_OF_FIRE
    - KAIN
    - KOSTOLOMISHE
    - CHEMER
    - UBEITSA
    - SKORCHEN
    - KORKUSHA
    - OGNEVITSA
  Boss:
    - LOMOTA
    - CHAINS_OF_FIRE
    - KAIN
    - KOSTOLOMISHE
    - CHEMER