Name: Река Омур
AbilityType: RIVER_OMUR
Upgrade: RIVER_OMUR_UP
TargetType: SELF
Sprite: CrossAbility
GoldCost: 6
Effects:
- EffectType: STATUS
  MinValue: 2
  MaxValue: 3
  VisualEffect:
    VisualEffectType: CROSS
    ReadyTrigger: Word
    WrapUpTime: 0.200000003
  StatusEffectType: AllyDamageIncrease

