Name: Адовы углища
AbilityType: DEMON_FIRE_COALS
TargetType: ENEMY
Intention: DEBUFF
AbilitySpellType: STATUS
Sprite: DEMON_FIRE_COALS
GoldCost: 3
Effects:
- EffectType: STATUS
  StatusEffectType: Waste
  MinValue: 6
  MaxValue: 6
  VisualEffect:
    VisualEffectType: SIMPLE_ATTACK
    ReadyTrigger: Attack
    SpellTrigger: Attack
    MissTrigger: Miss
    WrapUpTime: 0.100000001
    SkipReady: true

