Name: Аминь
AbilityType: AMEN_ROGUELIKE
AbilityBookPartType: KEY
Upgrade: AMEN_UP
TargetType: SELF
Intention: BUFF
Color: WHITE
AbilitySpellType: STATUS
Sprite: AMEN
GoldCost: 15
Effects:
- EffectType: FIRM
  MinValue: 1
  MaxValue: 1
- EffectType: STATUS
  MinValue: 2
  MaxValue: 2
  VisualEffect:
    ReadyTrigger: Word
    SpellTrigger: AttackSpell
    MissTrigger: AttackSpell
    WrapUpTime: 0.5
  StatusEffectType: Piety

