Name: The Vodyanoi's Chambers
Description: I will meet Vakul here. He will hopefully be able to break the seal at once.
ShortQuestDescr: Go to the vodyanoi's chambers
LongQuestDescr: The mermaid says that we're approaching Vakul's palace. I hope she's not leading me into another trap!

