AssetName: Demon
Health: 13
HealthRandomAdd: 7
Mana: 4
Initiative: 1
MoneyMin: 2
MoneyMax: 4
Experience: 50
UnitAI:
  AIAbilities:
  - AbilityType: DEMON_ATTACK
    TargetType: ENEMY
    ConsequitiveRounds: 2
  CastingType: RANDOM
Name: Чёрт

