Name: 悪魔の宮殿
Description: 毒々しい茸が一面に生えるこの場所に、謎めいた宮殿が建っている。悪魔はこの宮殿に、何百年も君臨し続けているのだ…
ShortQuestDescr: 願いを叶える
LongQuestDescr: 願いを叶えるためには地獄の中心にたどり着く必要がある。最初の障害となるのは、地獄におけるこの層の君主、アンドロマリウスだ。
LevelConfig:
  Battle:
    Name: アンドロマリウス

