TypeToLocalizationKey:
  PROFILE: ProfileScreenName
  INVENTORY: InventoryScreenName
  BOOK_PROFILE: BlackBook
  STORE: BuyPageScreenName
  JOURNAL: JournalScreenName
  ONOMASTIKON: OnomastikonScreenName
  ENCYCLOPEDIA: EncyclopediaScreenName
  MAP: MapScreenName
  DEMONS: DemonScreenName
  SKILLS: SkillsScreenName
  SKILLS_ROGUELIKE: SkillsScreenName
  ABILITY_SELECTION: BlackBook
  DECK_VIEW: BlackBook
  DECK_ROGUELIKE: DeckRoguelikeScreenName
SceneNameToBGName:
#Empty, Izba, LowGrass, OldInterior, PlanksLow, TreeBigFenceLeft, TreeBushes, TreeDense, TreeDense2, TreeFence, TreeSmallTop
  Fireplace: LowGrass
  Izba_EgorIntro2: Izba
  Hell: PlanksLow
  WindmillExploration: OldInterior
  Pits: TreeDense
  Rift: TreeDense2
  River_3: LowGrass
  River: LowGrass
  Izba_Peasant1: PlanksLow
  Izba_Peasant3: PlanksLow
  PolenoOld: TreeSmallTop
  Church: PlanksLow
  Village: LowGrass
  Village3: LowGrass
  Cemetery: TreeFence
  Marshes: LowGrass
  Marshes2: LowGrass
  LakeBank: LowGrass
  Izba: Izba
  ChurchNew: PlanksLow
  ChurchEmpty: OldInterior
  Fair: PlanksLow
  Sauna: OldInterior
  ChurchOld: OldInterior
  TkachihaIzba: OldInterior
  ObderihasNest: OldInterior
  ObderihasNest2: OldInterior
  ObderihasNest3: OldInterior
  HellInitiation: PlanksLow
  CrossroadsExploration: TreeSmallTop
  RavenForest: TreeSmallTop
  Karnysh: TreeSmallTopKarnysh
  BrideHouse: PlanksLow
  Forest: TreeSmallTop
  Forest_2: TreeDense
  Forest_3: TreeDense
  Road_3: LowGrass
  SaltFabricEvening: PlanksLow
  SaltVarnitsa: PlanksLow
  SaltFabric: PlanksLow
  SaltHouse: OldInterior
  SaltSauna: PlanksLow
  AyratIzba: Izba
  PrisonRe: Prison
  FinalFight: LowGrass