Name: 水底の小さな洞窟
Description: 洞窟はヴォジャノーイの縄張りの奥へと続いている。
ShortQuestDescr: 洞窟に向かう
LongQuestDescr: 湖に落ちたヴァシリーサがいたのは、ヴォジャノーイの縄張りだった。ルサールカはヴァシリーサのことを知っていたため、ヴァクルは彼女を案内役として送った。この女魔物はどこへ連れていこうとしているのだろうか？
LevelConfig:
  Battle:
    Name: カマス

