Name: Carpenter House
Description: The carpenters established their own plant here, in Anbor. Why would anyone pay them, when you can always count on helping hands?
ShortQuestDescr: Talk to the Carpenters

