Name: Змеиное жало
AbilityType: SNAKE_STING
AbilityBookPartType: KEY
TargetType: SELF
Intention: DEBUFF
AbilitySpellType: STATUS
Sprite: SNAKE_STING
GoldCost: 16
Effects:
- EffectType: STATUS
  MinValue: 1
  MaxValue: 1
  VisualEffect:
    VisualEffectType: KILA
    ReadyTrigger: Word
    SpellTrigger: Seal2KeyBlack
    MissTrigger: Seal2KeyBlack
    WrapUpTime: 0.200000003
    SkipReady: true
  StatusEffectType: DamageOnHealthLoss
  StatusPermanent: true

