Name: 三位一体教会
Description: この教会は、ヴィルゴルトで一番景色のいい、北側の斜面の上に建っている。白い石で造られていて、夜になると輝いているようにすら見える。太陽の光の元なら、もっと明るく輝く。
ShortQuestDescr: メノロギウムから名前を授かる
LongQuestDescr: キリスト教徒はメノロギウムから名前を授かる。そのため、ヴァシリーサはバーニャの花嫁につける名前を求めて、三位一体教会へと向かうことになった。

