Name: Near Tsidovka River
Description: The small river is wrapped in a damp fog. We were on the hill just a moment ago, and everything was visible. Can't see anything now.
ShortQuestDescr: Missing Peasants

