Name: Bondujinka River
Description: He was buried outside the churchyard... a wicked one he was. There's no reason to doubt it, one glance is enough to know.
ShortQuestDescr: Visit Levonty's grave

