AssetName: WhiteHeadAllyRegular
Health: 9999
HealthRandomAdd: 5
Mana: 4
Initiative: 2
UnitAI:
  AllyActivatedAbility:
    AbilityType: WHITE_HEAD_REGULAR
    TargetType: PLAYER
  AllyActivatedAbilityTimeout: 4
  CastingType: RANDOM
Name: Левонтий

