Name: Огненный барьер
AbilityType: FIRE_BARRIER
TargetType: ENEMY
Intention: DEBUFF
Sprite: FIRE_BARRIER
Effects:
- EffectType: STATUS
  StatusEffectType: Spikes
  MinValue: 5
  MaxValue: 5
- EffectType: STATUS
  StatusEffectType: DefenceKeep
  MinValue: 10
  MaxValue: 10
- EffectType: DEFENCE
  MinValue: 7
  MaxValue: 7
  VisualEffect:
    VisualEffectType: SIMPLE_ATTACK
    ReadyTrigger: Spell
    SpellTrigger: Spell
    MissTrigger: Miss
    SkipReady: true

