Name: 织婆的小屋
Description: 织婆的小屋就在皮亚涅村边上，这个女巫是个法力强大的万事通，连维葛特的乡亲都知道她这号人。有些女孩还专门去找她配过春药，因为叶戈尔爷爷不配那种东西。
ShortQuestDescr: 请织婆编裤带
LongQuestDescr: 你们决定请女巫“织婆”编一条有魔力的裤带。老叶戈尔跟你一起过去。织婆法力强大，你说不定需要他帮忙。
LevelConfig:
  Battle:
    Name: 邪灵

