Name: Вкус боли
AbilityType: PAIN_TASTE_SMALLEST
TargetType: ENEMY
Intention: DEBUFF
Sprite: PAIN_TASTE
Effects:
- EffectType: STATUS
  StatusEffectType: Poison
  MinValue: 1
  MaxValue: 1
- EffectType: STATUS
  StatusEffectType: Waste
  MinValue: 1
  MaxValue: 1
- EffectType: STATUS
  StatusEffectType: Decomposure
  MinValue: 1
  MaxValue: 1
- EffectType: STATUS
  StatusEffectType: Cursed
  MinValue: 1
  MaxValue: 1
  VisualEffect:
    VisualEffectType: SIMPLE_ATTACK
    ReadyTrigger: Spell2
    SpellTrigger: Spell2
    MissTrigger: Miss
    SkipReady: true

