Name: Душу тянуть
AbilityType: ERETNIK_VAMP
TargetType: SELF
Intention: BUFF
AbilitySpellType: STATUS
Sprite: ERETNIK_VAMP
GoldCost: 5
Effects:
- EffectType: STATUS
  StatusEffectType: Vampirism
  MinValue: 20
  MaxValue: 20
  VisualEffect:
    VisualEffectType: SIMPLE_ATTACK
    ReadyTrigger: Spell
    SpellTrigger: Spell
    MissTrigger: Miss
    SkipReady: true

