Name: Church of Transfiguration
Description: Old churches keep many secrets. It looks like the Church of Transfiguration still has some hidden away.
ShortQuestDescr: Learn of Proshka's past
LongQuestDescr: Your ikota-cat has been trying fruitlessly to recollect his past for several days now. It seems that the Yanidor church basement may uncover some glimpses of Proshka's susedko past. Was he really one of Chud's people, or was he born an evil spirit?

