Name: Vishera's Tears
Description: They say that the heroic Polud was loved by a girl called Vishera. I don't remember how the story goes, but her tears are all that remain. The spring bears her name.
LevelConfig:
  Battle:
    Name: Mermaid of Polud

