Name: Hell's Lake
Description: This is the lake Old Egor told me about. Various types of evil spirits are often seen here. This is because the border between worlds is thin here.
ShortQuestDescr: Find the Entrance to Vodyanoi Domain
LongQuestDescr: You drove off the mermaid, but the brine has gone away with her. The seal on your Book is still intact. Looks like only the master of the water domain will be able to deal with it.

