Name: Odolen-Herb
Flavour: Odolen-Herb! I was not the one who watered you, nor was I the one who gave birth to you. Mother Earth birthed you, and bareheaded girls and free-spirited women watered you.

