Name: 水車小屋
Description: 水車小屋は縁起の悪い場所だと思われがちだ。なぜなら、粉挽きはしばしば、ヴォジャノーイと取引を交わすからだ。
ShortQuestDescr: ヴォジャノーイと話す
LongQuestDescr: 酒場でヴァシリーサが出会ったのは、チョルトの姿となった野盗たちであった。この事件のことをヴァクルに詳しく話さなくては。
LevelConfig:
  Battle:
    Name: ヴォジャノーイ

