Name: Алатырь
AbilityType: ALTAR
Upgrade: ALTAR_UP
AbilityBookPartType: KEY
TargetType: SELF
Color: WHITE
Sprite: AltarAbility
GoldCost: 18
Effects:
  - EffectType: HEAL_SKLAD
    MinValue: 1
    MaxValue: 1
    VisualEffect:
      ReadyTrigger: Word
      SpellTrigger: GoodStatus
      MissTrigger: GoodStatus
      WrapUpTime: 0.200000003
      SkipReady: true
  - EffectType: KRADA

