Name: 古いバーニャ
Description: バーニャでは火事がよく起きる。ときどき、火を強く焚き過ぎる人がいるからだ。川べりに建てられることが多いのはそのためである。最近は、こうして火事になったバーニャのいくつかがそのままになっている。
ShortQuestDescr: 取り替え子を救い出す
LongQuestDescr: 取り替え子をオブジェリーハから解放するために必要なものが全て揃った。あとは、古いバーニャに行って彼女を救い出すだけだ！

