Name: 률빈 늪지대
Description: 야니도르 마을 근처에는 아름답지만 위험한 률빈 늪지대가 자리하고 있다. 이고르 할아버지가 말씀하시길 그 늪지대에는 악마들이 산다고 한다. 그렇다면 내 책을 위해 그 악마들을 잡을 수 있겠지.
ShortQuestDescr: 늪지대의 악마 잡기
LevelConfig:
  Battle:
    Name: 늪지대 악마

