Name: Vorys-sin
Description: Here I will face the leshiy.
ShortQuestDescr: Wake the Leshiy Up
LongQuestDescr: The son of Vorsa the Leshiy will wake him up when you get to his lair. Vorsa will set you free and break the next seal of the Black Book.

