Name: Огнеястра +
AbilityType: OGNEYASTRA_UP
TargetType: ENEMY
Intention: ATTACK
Sprite: KilaAbility
GoldCost: 16
Effects:
- MinValue: 15
  MaxValue: 15
  VisualEffect:
    VisualEffectType: KILA
    ReadyTrigger: Word
    SpellTrigger: AttackSpellSimple
    MissTrigger: AttackSpellSimple
    WrapUpTime: 0.200000003
    SkipReady: true
- EffectType: KRADA

