Name: 診療所
Description: 村は、病気の治療ができる大きな診療所を建てた。少なくとも、治療をしようとはしたのだ。だけど、彼らはコルドゥンではない。こうした「治療」のせいで、熱病が引き起こされてしまった。
ShortQuestDescr: 熱病で死んだ人間の遺体の脂を使ってろうそくを作る
LongQuestDescr: 熱病がイスコラに蔓延しているらしい。熱病が広がれば、待っているのは死だ。

