Name: ヤニドル
Description: この村の人々は意志が強い。ポホヂャシンの工場で何人かの村人が無理やり働かされそうになったが、村人たちは遠すぎて不便だと言って反乱を起こしたのだった。
ShortQuestDescr: 魔物が身につけていた十字架を見つける
LongQuestDescr: エゴールじいさんの話では、ヤニドルにイコニツァがいるらしい。バーニャの花嫁に渡す十字架をイコニツァから手に入れるため、ヴァシリーサはニコライと共にこの村に向かった。

