AssetName: ObderihaDemon
Health: 13
HealthRandomAdd: 5
Mana: 4
Initiative: 1
MoneyMin: 1
MoneyMax: 2
Experience: 100
UnitAI:
  AISpecialAbilities:
  - AbilityType: OBDERIHA_DEMON_POISON
    DecisionType: DOES_NOT_HAVE_STATUS
    TargetType: PLAYER
    SpecialData: Poison
  AIAbilities:
  - AbilityType: OBDERIHA_DEMON_ATTACK
    TargetType: ENEMY
    ConsequitiveRounds: 2
  CastingType: RANDOM
Name: Угольё

