Name: ねぐらの近く
Description: ある集いで一人のペルミの住人に会った。彼はポリュドフとコルチムの戦いについて教えてくれた。二人は互いに石を投げ合い、それがあまりにも長く続いたので、神は二人を山に変えてしまったのだという。
ShortQuestDescr: 来賓を救い出す
LongQuestDescr: どうやら、狼人間たちはポリュドフの森の精に囚われていたようだ。彼らが完全に獣に変わってしまう前に救い出さなければ。
LevelConfig:
  Battle:
    Name: 狼人間

