IdName: Week3Day1Grave
Name: У могилы
Description: Не за церковной оградой схоронен...
ShortQuestDescr: Сходить на могилку
LongQuestDescr: Дед Егор говорит, что время есть. Я решила сходить на могилу, проверить своего милого.
Scene: GraveIntro
LevelConfig:
  Quest:
    DialogueSystemName: TextQuest/Week3/Day1/GraveMonologue
    NoPortraitsIntro: true
  Exploration: Week3Day1Grave
  MusicOverride: event:/Music/Explore2
  NoExplorationMusic: true
  NoExplorerSpawn: true
RequiredLocations:
- Week3Day1Field
LockedAllies:
- Nikolay
- NikolayLoyal
- DedEgor
- DedEgorLoyal
- WhiteHead
- WhiteHeadLoyal
- Karnysh
- KarnyshLoyal
- Proshka
- ProshkaLoyal

