Name: Verhne-Chugrumsk Swamp
Description: The swamp is so overgrown with moss that it looks like the back of some huge beast partially buried underground. I've heard stories of Mang-Ont. Could this be it?

