Name: 삼위일체의 교회
Description: 북쪽 비탈 위에 서 있는 이 교회는 빌고르트에서 가장 경치가 좋은 곳이다. 교회는 하얀색 돌로 지어져 밤에는 은은하게 빛나는 듯하며, 햇빛 아래에서는 더욱 밝게 빛난다!
ShortQuestDescr: 메놀로기온에서 이름 찾기
LongQuestDescr: 기독교인은 메놀로기온에서 이름을 따오기 때문에, 당신은 반야의 신부에게 붙일 이름을 찾기 위해 빌고르트의 삼위일체의 교회로 향합니다.

