Name: Еретника дружина
AbilityType: ERETNIK_SQUAD
AbilityBookPartType: KEY
TargetType: ENEMY
Sprite: ERETNIK_SQUAD
GoldCost: 26
Effects:
- EffectType: KRADA
- EffectType: DAMAGE_FOR_NOT_WORKING_DEMONS
  MinValue: 3
  MaxValue: 3
  VisualEffect:
    VisualEffectType: KILA
    ReadyTrigger: Word
    SpellTrigger: Seal3KeyBlack
    MissTrigger: Seal3KeyBlack
    WrapUpTime: 0.2
    SkipReady: true
