Name: The Spinner's Izba
Description: This cursed izba again... There's no time to wait for grandpa's help, I'm getting the Book on my own!
ShortQuestDescr: Get Back the Black Book
LongQuestDescr: The Spinner took your witching manuscript! You went to her izba in search of the most valuable artifact in the entire gubernia.

