Name: Нетленные ризочки
AbilityType: RIZI_SMALL
TargetType: SELF
Intention: BUFF
Color: WHITE
AbilitySpellType: STATUS
Sprite: RIZI
GoldCost: 22
Effects:
- EffectType: STATUS_SKLAD
  MinValue: 1
  MaxValue: 1
  VisualEffect:
    VisualEffectType: CROSS
    ReadyTrigger: Word
    SpellTrigger: Seal5OrderWhite
    MissTrigger: Seal5OrderWhite
    WrapUpTime: 0.2
    SkipReady: true
  StatusEffectType: Imperishable

