Name: Уразы
AbilityType: URAZI
Upgrade: URAZI_UP
TargetType: ENEMY
Intention: ATTACK
Sprite: URAZI
GoldCost: 9
Effects:
- MinValue: 4
  MaxValue: 4
  VisualEffect:
    VisualEffectType: KILA
    ReadyTrigger: Word
    SpellTrigger: AttackSpellSimple
    MissTrigger: AttackSpellSimple
    WrapUpTime: 0.200000003
    SkipReady: true

