IdName: Week5Day5Fair
Name: Ивановская ярмарка
Description: Крестьяне устроили шумную ярмарку в честь праздника.
Scene: Fair
LevelConfig:
  MixerSnapshot: snapshot:/Village
  Merchants:
  - Peddler3
  - Herbalist3
  - BookKeeper3
  - CardGame
  Quest:
    DialogueSystemName: TextQuest/Week5/Day5/Fair/Intro
  MusicOverride: event:/Ambient/Yarmarka
  FoolGame:
    TeamPlay: true
    CardsCount: 36
    PlayerCount: 4
    PossiblePlayers:
    - Peasant
    - Peddler
    - Peasant
    - Peasant2
    - Peasant3
    - Peasant4
    - Peasant5
    - Peasant6
    - Peasant7
    - Peasant8
    DialogueFoolWin: TextQuest/Durak/MerchantGameWin
    DialogueFoolLose: TextQuest/Durak/MerchantGameLose
RequiredLocations:
- Week5Day5Crossroads
OnomastikonItems:
- Onomastikon/Tales/39

