Name: Егорий Батюшка
AbilityType: GEORGY_BATUSHKA_ROGUELIKE
Upgrade: GEORGY_BATUSHKA_UP
TargetType: SELF
Intention: BUFF
Color: WHITE
AbilitySpellType: STATUS
Sprite: GEORGY_BATUSHKA
GoldCost: 13
Effects:
- EffectType: STATUS_SKLAD
  MinValue: 1
  MaxValue: 1
  VisualEffect:
    VisualEffectType: NONE
    ReadyTrigger: Word
    SpellTrigger: GoodStatus
    MissTrigger: GoodStatus
    WrapUpTime: 0.5
  StatusEffectType: Blessed

