Presets:
  Onomastikon:
    - Onomastikon/
  Prologue:
    - HellInitiation
    - TextQuest/Week1/Day1/
    - TextQuest/Merchant/
    - TextQuest/Herb/
    - TextQuest/Artefact/
    - TextQuest/Util/
    - TextQuest/Priest/
    - TextQuest/Singers/
    - TextQuest/Durak/
    - Tutorial/Initiation/
    - UI/LooseScreenMessages
    - Izba/Tutorials/
    - Izba/Quests/IQMBodyMill
    - Izba/Quests/IQMBodyBath1
    - Izba/Egor/IzbaEgor1
    - Izba/Egor/IzbaEgor1
    - Izba/Explore/
    - Izba/Nikolay/Conv0
    - Izba/Nikolay/Conv1
    - Izba/Week1/
    - Izba/Banter/EgorNikolay
    - Exploration/Mill/
    - Exploration/Crossroads1/
    - Exploration/CrossroadsApproach/
    - Exploration/HellInitiation/Dialogue
    - Exploration/Bath1/
    - Exploration/Bath2/
    - Exploration/GraveIntro/
    - Intro
    - Job/
    - Battle/
  Week 1 and Allies:
    - TextQuest/Week1/
    - TextQuest/AllyProshka/
    - TextQuest/AllyEgor/
    - TextQuest/AllyNikolay/
    - TextQuest/AllyHead/
    - TextQuest/AllyKarnysh/
    - Izba/Egor/
    - Izba/Nikolay/
    - Izba/Week1/
    - Izba/Context/
    - Izba/WhiteHead/
    - Izba/Karnysh/
    - Izba/Proshka/
    - Izba/Banter/
    - Exploration/HellInitiation/
    - Exploration/Week1/
  Week 2:
    - Izba/Quests/
    - Exploration/Week2/
    - TextQuest/Week2/
    - Izba/Week2/
  Week 3:
    - TextQuest/Week3/
    - Izba/Week3/

  Week 4:
    - TextQuest/Week4/
    - Izba/Week4/

  Week 5:
    - TextQuest/Week5/
    - Izba/Week5/

  Week 6:
    - TextQuest/Izba/
    - TextQuest/Week6/
    - Izba/Week6/

  Week 7:
    - TextQuest/Week7/
    - Izba/Week7/

  Onomastikon/Encyclopedia:
    - Onomastikon/Encyclopedia
  Onomastikon/Tales:
    - Onomastikon/Tales
  Onomastikon/Songs:
    - Onomastikon/Songs
  EnglishVOTest:
    - Tutorial/Initiation/InitiationBattle
  EnglishVO:
    - Exploration/GraveIntro/VasilisaMonologue
    - Exploration/Crossroads1/DedEgorTalk
    - Tutorial/Initiation/InitiationBattle
    - Tutorial/Initiation/Initiation1
    - Tutorial/Initiation/Initiation3
    - Tutorial/Initiation/Initiation4
    - Tutorial/Initiation/Initiation5Idle
    - Tutorial/Initiation/Initiation6
    - Izba/Tutorials/IzbaInit
    - Izba/Tutorials/IzbaInit2
    - Izba/Tutorials/Demons
    - Izba/Quests/IQMBodyMill
    - Izba/Quests/IQMBodyBath1
    - Izba/Quests/Week2Solevar
    - Izba/Quests/Week3Day2Niko
    - Exploration/Week1/IzbaNextQuest
    - Exploration/Week1/Name/IzbaAftermath
    - Exploration/Week1/Tkachiha/IzbaAftermath
    - Exploration/Week1/Ikota/IzbaAftermath
    - Exploration/HellInitiation/*
    - Izba/Egor/IzbaEgor1
    - Izba/Egor/AllyQuestGive
    - Izba/Egor/Aftermath
    - Izba/Egor/
    - TextQuest/AllyEgor/Cemetery/ProkopiyDialogue
    - Izba/Nikolay
    - Izba/Nikolay/Conv1
    - Izba/Proshka
    - TextQuest/AllyProshka/Limbo/ProshkaTalk
    - Izba/WhiteHead
    - Exploration/Week1/Tkachiha/SkullConv
    - Izba/Karnysh
    - Izba/Week2/Day13
    - Izba/Week2/Day14
    - Izba/Week2/Day10
    - Izba/Week3/Day15
    - Izba/Week3/Day17
    - Izba/Week3/Day19
    - TextQuest/Week3/Day1/Pryaha
    - TextQuest/Week3/Day1/GraveMonologue
    - TextQuest/Week3/Day3/BeforeBath/Intro
    - TextQuest/Week3/Day3/Yard/IntroConversation
    - TextQuest/Week3/Day4/Depart/Dialogue
    - TextQuest/Week3/Day4/Stopped/DedEgorIntro
    - TextQuest/Week3/Day7/NearLair/FedkaSaved
    - TextQuest/Week3/Day7/Lair/Niko
    - Izba/Week4/Day22
    - Izba/Week4/Day23Main
    - Izba/Week4/Day24Efim
    - Izba/Week4/Day25Thinking
    - Izba/Week4/Day26Efim
    - Izba/Week4/Day27Thinking
    - TextQuest/Week4/Day1/Map3/Village/Talk
    - TextQuest/Week4/Day2/Crossroads/RitualRavenTalk
    - TextQuest/Week4/Day3/Stump/RavenFinalTalk
    - TextQuest/Week4/Day3/Stump/RavenTalkBad
    - TextQuest/Week4/Day3/Stump/GalinaTalk
    - TextQuest/Week4/Day4/Hunter/Dialogue
    - TextQuest/Week4/Day4/Shepard/Dialogue
    - TextQuest/Week4/Day6/Forest/Conversation
    - TextQuest/Week4/Day6/Stump/Dialogue
    - TextQuest/Week4/Day6/StumpUnder/FilimonPreBattle
    - TextQuest/Week4/Day7/Leshy/FilimonReady
    - TextQuest/Week4/Day7/Leshy/RavenReady
    - Izba/Week5/Day27EgorIntro
    - Izba/Week5/Day27Niko
    - Izba/Week5/Day28Niko
    - Izba/Week5/Day31PaporotIntro
    - TextQuest/Week5/Day1/VilgortChurch/Alexander
    - TextQuest/Week5/Day1/VilgortChurch/Alexander
    - TextQuest/Week5/Day3/Church/SavelyInside
    - TextQuest/Week5/Day3/Church/Door
    - TextQuest/Week5/Day5/KolvaFires/Nikolay
    - TextQuest/Week5/Day5/KolvaFires/Fedka
    - TextQuest/Week5/Day5/KolvaFires/Solevar
    - TextQuest/Week5/Day5/KolvaFires/Samson
    - Izba/Week6/PreEgor
    - Izba/Week6/PrePryaha
    - TextQuest/Week6/Day1/Prison/IntroAlex
    - TextQuest/Week6/Day1/AlexanderOffice/Dialogue
    - TextQuest/Week6/Day2/Book/PryahaTalk
    - TextQuest/Week6/Day3/Grave/Prichet
    - TextQuest/Week6/Day3/Field/Dialogue
    - TextQuest/Week6/Day3/Field/PreBattle
    - TextQuest/Week6/Day3/SkyBattle
    - TextQuest/Week6/Day3/Crossroads/PreBattle
    - TextQuest/Week6/Day3/Crossroads/AfterBattle1
    - TextQuest/Week6/Day3/Crossroads/AfterBattle2
    - Izba/Week7/FatherIntro
    - Izba/Week7/Day2Father
    - Izba/Week7/Day3Father
    - Izba/Week7/Day1Father
    - Izba/Week7/Day2FatherBanter
    - TextQuest/Week7/Day3/Throne/Dialogue
    - TextQuest/Week7/Day3/Throne/PrePahseTwo
    - TextQuest/Week7/Day3/Throne/Outro
    - TextQuest/Week7/GameOver/OutroAllies
    - Intro
    - Izba/Week1/Bath1Aftermath
    - Izba/Week1/MillAftermath
    - Izba/Week1/MillAftermathMiller
    - Izba/Week1/NikolayCardGift
    - Exploration/Mill/Conversation
    - Exploration/Bath1/Conversation
    - Exploration/Bath2/Conversation*
    - Exploration/Week1/Ikota/ConversationIkota
    - Exploration/Week1/Tkachiha/TkachihaConv
    - Exploration/Week1/Obderiha/ObderihaConv
    - Exploration/Week1/Obderiha/ObderihaConvBride
    - Exploration/Week1/Obderiha/ObderihaConvChest
    - Exploration/Week1/Obderiha/BadChoice
    - Exploration/Week1/Obderiha/ObderihaBattleConv
    - Exploration/Week1/Obderiha/ObderihaDead2
    - Exploration/Week2/Zemskaia/Dialogue