IdName: IzbaPike
Name: Подводный привал
Scene: PikeNestIzba
IsIzba: true
LevelConfig:
  MixerSnapshot: snapshot:/Underwater
  MusicOverride: "event:/Music/Izba"
  SpecialLevel: true
  FoolGame:
    CardsCount: 36
    PlayerCount: 4
ForbiddenSpawnAllies:
- DedEgor
- DedEgorLoyal
- Nikolay
- NikolayLoyal
AdditionalIzbaFoolPlayers:
  - Mermaid
