Name: アレクサンドルの執務室
Description: アレクサンドルは執務室にいる。私が脱獄しているとは、夢にも思ってないだろう。
ShortQuestDescr: 薬草と禁遺物を取り戻す
LongQuestDescr: アレクサンドルは黒の書だけでなく、ヴァシリーサの持ち物全てを取り上げた。黒の書は後で糸繰りから取り戻すとして、まずは持ち物を取り戻さなければ。
LevelConfig:
  Battle:
    Name: 三位一体

