Name: 소굴 근처
Description: 어떤 집회에서 만난 페름 주민에게서 폴루트와 콜침의 싸움에 대해 들은 적이 있다. 그들은 어찌나 오랫동안 서로에게 돌을 던졌는지, 신께서 둘 다 산으로 만들어 버렸다고 한다.
ShortQuestDescr: 하객 구하기
LongQuestDescr: 늑대인간들은 폴루트 숲의 정령에게 사로잡힌 모양입니다. 그들이 완전히 짐승으로 변하기 전에 풀어줘야 합니다.
LevelConfig:
  Battle:
    Name: 인랑

