Name: Тірöб му
AbilityType: MENQW_TYROB
AbilityBookPartType: KEY
TargetType: ENEMY
Intention: ATTACK
Sprite: MENQW_TYROB
GoldCost: 10
Effects:
- MinValue: 5
  MaxValue: 10
  VisualEffect:
    VisualEffectType: KILA
    ReadyTrigger: Word
    SpellTrigger: Attack
    MissTrigger: Attack
    WrapUpTime: 0.200000003
    SkipReady: true

