Name: 빌고르트 묘지
Description: 빌고르트 사람은 전부 이곳에 묻힌다. 한때는 사람만이 묻혔지만, 이제는 죽은 동물도 묻혀있다. 오싹하기도 하지.
ShortQuestDescr: 묘지 초르트 잡기
LongQuestDescr: 누군가가 빌고르트 묘지 예배당의 소를 갈기갈기 찢어놨습니다. 당신과 이고르 할아버지는 그 기이한 악마를 잡기 위해 빌고르트 묘지로 향했습니다.

