Name: Small banya by the riverbank
Description: Banyas are prone to fires; people stoke the flames too hard at times. That's why they're often built on riverbanks. Nowadays, some of these banyas are abandoned.
ShortQuestDescr: Talk with the demoness in the banya
LongQuestDescr: Your visitor promised the bath demoness that he would marry her. You set forth to the old banyas with Nikolay to talk with the spirit.

