Name: Kulyashov Farmstead
Description: Curved Ravine's bad reputation didn't stop the Kulyashovs from building a prosperous farmstead nearby. As far as I know, they live pretty well.
ShortQuestDescr: Cure the Cow

