Name: Fires Near the Kolva
Description: The residents of Vilgort have built a fire and dance in circles. The girls are probably going to do divinations. I don't need divinations – I already know my destiny!

