Name: 地獄沼
Description: エゴールおじいちゃんが言っていたのはこの湖だ。ここには色々な魔物が出没する。この世とあの世の境界が薄くなっているからだ。
ShortQuestDescr: ヴォジャノーイの縄張りの入口を見つける
LongQuestDescr: ルサールカを追い払うことはできたが、塩水を持ち去られてしまった。黒の書の封印にはまだ何の変化もない。どうやら、封印を解くには水域の主の力が必要らしい。

