Name: Geltov Settlements
Description: Near Pyanteg, there are several small villages scattered throughout the nearby forests and woods. Seems like a nice place to live.
ShortQuestDescr: Investigate Petrov's fields

