IdName: Week1Day4Log
Name: Лог Плоской
Description: Крестьяне в этом логу заметили намедни большой вихрь и попросили проверить.
ShortQuestDescr: Выловить чертей в логу
Scene: Road_2
LevelConfig:
  MixerSnapshot: snapshot:/Forest
  MusicOverride: event:/Music/ExploreDark
  Battle:
    Name: Чертов вихрь
    Enemies:
    - Type: Demon
      LevelSpawnPointType: EnemyCenter
    - Type: DemonSummoner
    EnemyKillWin: true
    HealthLoose: true
  Quest:
    DialogueSystemName: TextQuest/Week1/Day4/Log
RequiredLocations:
- Week1Day4Abachkin

