Name: Mikhail's Crossroads
Description: These are the crossroads where my recent initiation took place. It is surely a place where both roads and human fates intersect.
LevelConfig:
  Battle:
    Name: Fierce Pair

