DayToTitle:
  1:
    Date: Chapter 1
    Title: How to Kidnap from a Banya
  7:
    Date: Chapter 2
    Title: How to Visit a Vodyanoi
  14:
    Date: Chapter 3
    Title: How Kolduns Curse Weddings
  21:
    Date: Chapter 4
    Title: How a Leshiy Walks the Forest
  26:
    Date: Chapter 5
    Title: How a Fern Blooms
  32:
    Date: Chapter 6
    Title: How Kolduns Die
  35:
    Date: Chapter 7
    Title: How Sinners Suffer in Hell

