Name: Моровые когти
AbilityType: PESTILENCE_CLAWS
TargetType: ENEMY
Intention: ATTACK
Sprite: PESTILENCE_CLAWS
GoldCost: 3
Effects:
- MinValue: 20
  MaxValue: 40
  VisualEffect:
    VisualEffectType: SIMPLE_ATTACK
    ReadyTrigger: Attack
    SpellTrigger: Attack
    MissTrigger: Miss
    SkipReady: true
- EffectType: STATUS
  StatusEffectType: Waste
  MinValue: 15
  MaxValue: 15

