Name: Tashkov Ravine
Description: There's no shortage of waterfalls and ravines when you travel around Cherdyn' Uyezd. They say further to the west one can even see mountains that surround the region.

