"""Glossary with longest-match placeholder protection.

Also provides corpus-driven glossary *discovery*: scan the source units for
recurring proper nouns / named entities so the glossary grows from the content
instead of a hand-maintained fix-list.
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

# Lowercase connector words allowed *inside* a multi-word proper noun, e.g.
# "Assembly of the People", "Markian Sea", "Duchess of Rumburgh".
_CONNECTORS = {
    "of", "the", "and", "for", "de", "von", "van", "der", "den", "la", "le",
    "du", "di", "da", "el", "al", "bin", "ibn", "ter", "ten",
}

# Capitalised words that are almost never game-specific named entities.
_STOPWORDS = {
    "the", "a", "an", "and", "or", "but", "so", "if", "then", "than", "as",
    "in", "on", "at", "to", "of", "for", "with", "by", "from", "into", "onto",
    "this", "that", "these", "those", "we", "you", "they", "he", "she", "it",
    "i", "me", "my", "our", "your", "their", "his", "her", "its", "us", "them",
    "there", "here", "what", "why", "how", "who", "whom", "whose", "where",
    "when", "which", "while", "yes", "no", "not", "now", "today", "tomorrow",
    "yesterday", "do", "does", "did", "is", "are", "was", "were", "be", "been",
    "being", "have", "has", "had", "will", "would", "can", "could", "should",
    "shall", "may", "might", "must", "let", "please", "thank", "thanks", "ok",
    "okay", "well", "sir", "madam", "mr", "mrs", "ms", "dr",
    "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday",
    "january", "february", "march", "april", "may", "june", "july", "august",
    "september", "october", "november", "december",
    "after", "before", "during", "since", "until", "although", "however",
    "meanwhile", "finally", "instead", "perhaps", "maybe", "also", "even",
    "because", "though", "unless", "whether", "once", "again", "another",
}

_TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z'\u2019\-]*")
_SENT_BREAK_RE = re.compile(r"[.!?\n]")
_POSSESSIVE_RE = re.compile(r"['\u2019]s?$")


@dataclass
class GlossaryRule:
    src: str
    tgt: str


def load_glossary(path: Path) -> list[GlossaryRule]:
    rules: list[GlossaryRule] = []
    if not path.exists():
        return rules
    for line in path.read_text("utf-8").splitlines():
        line = line.rstrip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 2 and parts[0]:
            rules.append(GlossaryRule(src=parts[0], tgt=parts[1]))
    rules.sort(key=lambda r: len(r.src), reverse=True)
    return rules


def protect(text: str, rules: list[GlossaryRule]) -> tuple[str, dict[str, str]]:
    """Replace glossary src terms with stable placeholders.

    Returns the protected text and a placeholder→target map so we can
    restore after the backend translates the surrounding text.
    """
    mapping: dict[str, str] = {}
    out = text
    for i, rule in enumerate(rules):
        token = f"⟦G{i}⟧"
        pattern = re.compile(re.escape(rule.src))
        if pattern.search(out):
            out = pattern.sub(token, out)
            mapping[token] = rule.tgt
    return out, mapping


def restore(text: str, mapping: dict[str, str]) -> str:
    out = text
    for token, tgt in mapping.items():
        out = out.replace(token, tgt)
    return out


# --- Corpus-driven glossary discovery -------------------------------------

_AUTO_BEGIN = "# >>> auto-glossary (generated by `tl glossary build`)"
_AUTO_END = "# <<< auto-glossary"


def detect_terms(
    texts: list[str], min_count: int = 5, max_terms: int = 400
) -> list[tuple[str, int]]:
    """Find recurring proper nouns / named entities in the source corpus.

    Heuristic, dependency-free NER:
      - Group consecutive Capitalised words (allowing lowercase connectors
        like "of"/"the" between them) into candidate phrases.
      - Multi-word phrases are strong signals: keep if seen >= min_count.
      - Single words must also appear mid-sentence (not only sentence-initial)
        at least once, be long enough, and not be a common stopword.

    Returns (term, count) ranked by frequency then length, capped at max_terms.
    """
    phrase_count: Counter[str] = Counter()
    single_total: Counter[str] = Counter()
    single_mid: Counter[str] = Counter()

    for text in texts:
        if not text:
            continue
        tokens: list[tuple[str, bool]] = []  # (word, is_sentence_initial)
        last_idx = 0
        for m in _TOKEN_RE.finditer(text):
            gap = text[last_idx : m.start()]
            is_init = m.start() == 0 or bool(_SENT_BREAK_RE.search(gap))
            tokens.append((m.group(0), is_init))
            last_idx = m.end()

        n = len(tokens)
        i = 0
        while i < n:
            word, is_init = tokens[i]
            if not word[0].isupper():
                i += 1
                continue
            run = [word]
            j = i + 1
            while j < n:
                wj, wj_init = tokens[j]
                # Never merge across a sentence boundary.
                if wj_init:
                    break
                if wj[0].isupper():
                    run.append(wj)
                    j += 1
                elif (
                    wj.lower() in _CONNECTORS
                    and j + 1 < n
                    and not tokens[j + 1][1]
                    and tokens[j + 1][0][0].isupper()
                ):
                    run.append(wj)
                    j += 1
                else:
                    break
            phrase = " ".join(run)
            if len(run) >= 2:
                phrase = _POSSESSIVE_RE.sub("", phrase)
                phrase_count[phrase] += 1
            else:
                word_norm = _POSSESSIVE_RE.sub("", phrase)
                if word_norm:
                    single_total[word_norm] += 1
                    if not is_init:
                        single_mid[word_norm] += 1
            i = j

    candidates: dict[str, int] = {}
    for phrase, c in phrase_count.items():
        if c >= min_count:
            candidates[phrase] = c
    for word, c in single_total.items():
        if (
            c >= min_count
            and single_mid[word] >= 1
            and len(word) >= 3
            and word.lower() not in _STOPWORDS
        ):
            candidates[word] = c

    ranked = sorted(candidates.items(), key=lambda kv: (-kv[1], -len(kv[0]), kv[0]))
    return ranked[:max_terms]


def write_glossary(path: Path, manual: list[GlossaryRule], auto: list[GlossaryRule]) -> None:
    """Rewrite glossary.tsv keeping a manual section and an auto-generated block.

    Manual entries appear first (and win on conflict); the auto block is
    delimited by markers so it can be regenerated without clobbering hand edits.
    """
    manual_keys = {r.src for r in manual}
    lines = ["# src\ttgt", "# Manual entries below take precedence over the auto block."]
    for r in manual:
        lines.append(f"{r.src}\t{r.tgt}")
    lines.append("")
    lines.append(_AUTO_BEGIN)
    for r in auto:
        if r.src in manual_keys:
            continue
        lines.append(f"{r.src}\t{r.tgt}")
    lines.append(_AUTO_END)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def split_glossary(path: Path) -> tuple[list[GlossaryRule], list[GlossaryRule]]:
    """Return (manual_rules, auto_rules) from an existing glossary.tsv."""
    manual: list[GlossaryRule] = []
    auto: list[GlossaryRule] = []
    if not path.exists():
        return manual, auto
    in_auto = False
    for line in path.read_text("utf-8").splitlines():
        stripped = line.strip()
        if stripped == _AUTO_BEGIN:
            in_auto = True
            continue
        if stripped == _AUTO_END:
            in_auto = False
            continue
        if not stripped or stripped.startswith("#"):
            continue
        parts = line.rstrip().split("\t")
        if len(parts) >= 2 and parts[0]:
            rule = GlossaryRule(src=parts[0], tgt=parts[1])
            (auto if in_auto else manual).append(rule)
    return manual, auto
