"""Minimal JSONC writer that preserves a leading schema banner + comments."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

_BANNER = (
    "// Auto-generated by tools/python/pcgw-fetch.\n"
    "// Re-run `uv run pcgw-fetch --refresh <path>` to update.\n"
    "// Add `\"_manual\": true` next to any field you hand-edit to prevent overwrite.\n"
)


def _strip_jsonc(text: str) -> str:
    """Strip // line comments and trailing commas for re-parsing."""
    no_line = re.sub(r"//[^\n]*", "", text)
    no_trailing = re.sub(r",(\s*[}\]])", r"\1", no_line)
    return no_trailing


def read_jsonc(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    return json.loads(_strip_jsonc(text))


def _merge_manual(existing: dict[str, Any], fresh: dict[str, Any]) -> dict[str, Any]:
    """Keep fields from `existing` where its sibling `_manual` is true."""
    if not existing.get("_manual"):
        # whole-doc opt-out
        pass

    def walk(old: Any, new: Any) -> Any:
        if isinstance(old, dict) and isinstance(new, dict):
            if old.get("_manual") is True:
                return old
            out = dict(new)
            for k, v in old.items():
                if k in out:
                    out[k] = walk(v, out[k])
            return out
        return new

    return walk(existing, fresh)


def write_metadata(path: Path, data: dict[str, Any], *, merge_existing: bool = False) -> None:
    if merge_existing and path.exists():
        try:
            existing = read_jsonc(path)
            data = _merge_manual(existing, data)
        except json.JSONDecodeError:
            pass

    path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(data, indent=2, ensure_ascii=False)
    path.write_text(_BANNER + body + "\n", encoding="utf-8")
