#!/usr/bin/env python3
"""
Generate keybinding presets for the DoW:DE Keybinding Overhaul mod.

Source of truth: mod/keybinds/stock/keydefaults.lua (a verbatim copy of
Engine/defprofile/keydefaults.lua unpacked from the game's Engine.sga).

Presets produced (under presets/<preset>/):

  - vanilla/        — identical to stock; ships so users can restore defaults
                      after experimenting with other presets.

  - wasd-camera/    — community fix: plain W/A/S/D pans the camera; action
                      bindings that previously occupied those bare letters
                      are prefixed with Shift+ to avoid collision.
                      REPLACES the Classic preset's keydefaults.lua.

  - wasd-camera-ingame/
                    — same WSAD transformation but installed as the engine's
                      Modern preset slot (`keydefaults_modern.lua`). The engine
                      hardcodes three preset filenames (classic / grid / modern)
                      and silently ignores any other name; overwriting Modern is
                      the only way to add a selectable in-game preset without
                      patching the binary.

For each preset, the lua file is placed at:
    presets/<preset>/Engine/defprofile/<filename>.lua

so the archive can be deployed straight to the game root by Vortex or by
manual extraction.

A per-preset HOTKEYS.md cheat sheet is also generated by parsing the lua
binding tables and rendering a category-grouped markdown table.

Run:
    uv run python scripts/build_keybind_presets.py
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
STOCK_LUA = REPO_ROOT / "stock" / "keydefaults.lua"
PRESETS_DIR = REPO_ROOT / "presets"

# Bare letters that the WSAD preset claims for camera pan.
CAMERA_LETTERS = {"W", "A", "S", "D"}

# Matches a key-binding line of the form:
#     identifier        = "Value",
# tolerant of any whitespace / tab indentation.
BINDING_LINE_RE = re.compile(
    r'^(?P<indent>\s*)(?P<key>[A-Za-z_][\w]*)(?P<eq>\s*=\s*)"(?P<value>[^"]*)"(?P<tail>,?\s*(?:--.*)?)$'
)


# ---------------------------------------------------------------------------
# Block detection — split stock file into (pre, bindings_body, between,
# camera_body, post) so we can apply different rewrite rules to each region.
# ---------------------------------------------------------------------------

def split_blocks(text: str) -> dict[str, str]:
    """Return the 5 textual regions of keydefaults.lua keyed by name."""
    lines = text.splitlines(keepends=True)

    def find(needle: str, start: int = 0) -> int:
        for i in range(start, len(lines)):
            if lines[i].lstrip().startswith(needle):
                return i
        raise ValueError(f"could not locate {needle!r} in keydefaults.lua")

    bindings_open = find("bindings =")
    # The opening "{" is on the line right after "bindings ="
    bindings_brace_open = bindings_open + 1
    bindings_brace_close = find("}", bindings_brace_open)

    camera_open = find("camera_bindings =", bindings_brace_close)
    camera_brace_open = camera_open + 1
    camera_brace_close = find("}", camera_brace_open)

    return {
        "pre": "".join(lines[: bindings_brace_open + 1]),
        "bindings_body": "".join(lines[bindings_brace_open + 1 : bindings_brace_close]),
        "between": "".join(lines[bindings_brace_close : camera_brace_open + 1]),
        "camera_body": "".join(lines[camera_brace_open + 1 : camera_brace_close]),
        "post": "".join(lines[camera_brace_close:]),
    }


# ---------------------------------------------------------------------------
# Transformations
# ---------------------------------------------------------------------------

def shift_prefix_collision(value: str) -> str:
    """In a comma-separated key list, prefix every bare W/A/S/D with `Shift+`.

    Tokens that already carry a modifier (`Control+`, `Shift+`, `Alt+`, or a
    multi-key combo) are left untouched. An empty value stays empty.
    """
    if not value:
        return value
    out = []
    for token in value.split(","):
        stripped = token.strip()
        if stripped in CAMERA_LETTERS:
            out.append(f"Shift+{stripped}")
        else:
            out.append(stripped)
    return ",".join(out)


def strip_shift_for_camera(value: str) -> str:
    """In camera_bindings, replace `Shift+W/A/S/D` tokens with the bare letter."""
    if not value:
        return value
    out = []
    for token in value.split(","):
        stripped = token.strip()
        m = re.fullmatch(r"Shift\+([WASD])", stripped)
        if m:
            out.append(m.group(1))
        else:
            out.append(stripped)
    return ",".join(out)


def rewrite_block(body: str, value_fn) -> str:
    """Apply `value_fn` to the value of every binding line in `body`.

    Preserves the original trailing newline sequence (LF or CRLF) per line.
    """
    out_lines = []
    for line in body.splitlines(keepends=True):
        # Detach trailing newline (\r\n or \n) so the regex can anchor cleanly.
        if line.endswith("\r\n"):
            content, eol = line[:-2], "\r\n"
        elif line.endswith("\n"):
            content, eol = line[:-1], "\n"
        else:
            content, eol = line, ""

        m = BINDING_LINE_RE.match(content)
        if not m:
            out_lines.append(line)
            continue
        new_value = value_fn(m.group("value"))
        rebuilt = (
            f'{m.group("indent")}{m.group("key")}{m.group("eq")}'
            f'"{new_value}"{m.group("tail")}'
        )
        out_lines.append(rebuilt + eol)
    return "".join(out_lines)


def build_wasd(stock_text: str) -> str:
    blocks = split_blocks(stock_text)
    new_bindings = rewrite_block(blocks["bindings_body"], shift_prefix_collision)
    new_camera = rewrite_block(blocks["camera_body"], strip_shift_for_camera)
    return blocks["pre"] + new_bindings + blocks["between"] + new_camera + blocks["post"]


# ---------------------------------------------------------------------------
# Cheat sheet generator
# ---------------------------------------------------------------------------

# Heuristic category mapping based on comment headers in the stock file.
SECTION_HEADER_RE = re.compile(r"^\s*--\s*([A-Z][A-Z _0-9/]+)\s*$")

# Identifier prefix → human-readable category (fallback for race-specific keys).
RACE_PREFIXES = {
    "marine_": "Space Marines",
    "chaos_": "Chaos",
    "ork_": "Orks",
    "eldar_": "Eldar",
    "ig_": "Imperial Guard",
    "guard_": "Imperial Guard",
    "necron_": "Necrons",
    "tau_": "Tau",
    "sisters_": "Sisters of Battle",
    "dark_eldar_": "Dark Eldar",
}


def parse_bindings(body: str) -> list[tuple[str, str, str]]:
    """Return list of (category, key, value) tuples for cheat sheet rendering."""
    current = "General"
    rows: list[tuple[str, str, str]] = []
    for raw in body.splitlines():
        header = SECTION_HEADER_RE.match(raw)
        if header:
            current = header.group(1).strip().title()
            continue
        m = BINDING_LINE_RE.match(raw)
        if not m:
            continue
        key = m.group("key")
        value = m.group("value")
        if not value:
            continue  # unbound
        category = current
        for prefix, race in RACE_PREFIXES.items():
            if key.startswith(prefix):
                category = race
                break
        rows.append((category, key, value))
    return rows


def render_cheatsheet(preset: str, stock_text: str, preset_text: str) -> str:
    blocks = split_blocks(preset_text)
    bindings_rows = parse_bindings(blocks["bindings_body"])
    camera_rows = parse_bindings(blocks["camera_body"])

    # Group bindings by category, preserving insertion order.
    groups: dict[str, list[tuple[str, str]]] = {}
    for cat, key, val in bindings_rows:
        groups.setdefault(cat, []).append((key, val))

    title_map = {
        "vanilla": "Vanilla (DoW:DE stock defaults)",
        "wasd-camera": "WSAD Camera (community fix, replaces Classic)",
        "wasd-camera-ingame": "WSAD Camera (in-game dropdown preset)",
    }
    out: list[str] = []
    out.append(f"# Hotkey Cheat Sheet — {title_map.get(preset, preset)}\n")
    out.append("")
    out.append(f"Auto-generated from `presets/{preset}/Engine/defprofile/keydefaults.lua`.")
    out.append("")
    out.append("## Camera")
    out.append("")
    out.append("| Action | Key |")
    out.append("|---|---|")
    for _, key, val in camera_rows:
        out.append(f"| `{key}` | `{val}` |")
    out.append("")
    for cat, items in groups.items():
        out.append(f"## {cat}")
        out.append("")
        out.append("| Action | Key |")
        out.append("|---|---|")
        for key, val in items:
            out.append(f"| `{key}` | `{val}` |")
        out.append("")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

PRESET_DEPLOY_PATH = Path("Engine") / "defprofile" / "keydefaults.lua"
# The engine hardcodes three preset filenames in W40k.exe / *Mod.dll:
#   keydefaults.lua, keydefaults_grid.lua, keydefaults_modern.lua
# Any other filename (e.g. keydefaults_wasd.lua) is silently ignored.
# So the in-game variant overwrites the Modern slot — the newest preset
# (Relic 2025 redesign), with the smallest installed base.
INGAME_DEPLOY_PATH = Path("Engine") / "defprofile" / "keydefaults_modern.lua"

# Keep the Modern locstring ($11271752 = "Modern Hotkeys") so the in-game
# dropdown entry text doesn't visually change — players who select "Modern"
# get WSAD. (The README documents this re-purposing.)
INGAME_LOCSTRING = "$11271752"


def retarget_ingame(text: str) -> str:
    """Rewrite the keydefaults_modern.lua header for the in-game dropdown slot.

    Replaces `bindings_locstring = "$<id>"` with the Modern locstring so the
    dropdown still reads "Modern Hotkeys" — the WSAD bindings live behind that
    label. bindings_version is left alone.
    """
    return re.sub(
        rb'bindings_locstring\s*=\s*"[^"]*"',
        f'bindings_locstring = "{INGAME_LOCSTRING}"'.encode("utf-8"),
        text.encode("utf-8"),
        count=1,
    ).decode("utf-8")


def write_preset(preset: str, lua_text: str, stock_text: str, dry_run: bool,
                 deploy_path: Path = PRESET_DEPLOY_PATH) -> None:
    preset_root = PRESETS_DIR / preset
    lua_path = preset_root / deploy_path
    cheatsheet_path = preset_root / "HOTKEYS.md"

    if dry_run:
        print(f"  [dry-run] would write {lua_path.relative_to(REPO_ROOT)} "
              f"({lua_text.count(chr(10))} lines)")
        print(f"  [dry-run] would write {cheatsheet_path.relative_to(REPO_ROOT)}")
        return

    lua_path.parent.mkdir(parents=True, exist_ok=True)
    # Preserve game-native CRLF line endings; Relic ships keydefaults.lua as CRLF
    # and we want the deployed file to be byte-identical to vanilla where possible.
    lua_path.write_bytes(lua_text.encode("utf-8"))
    cheatsheet_path.write_text(
        render_cheatsheet(preset, stock_text, lua_text), encoding="utf-8"
    )
    print(f"  ✓ {lua_path.relative_to(REPO_ROOT)}")
    print(f"  ✓ {cheatsheet_path.relative_to(REPO_ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--dry-run", action="store_true",
                        help="Print actions without writing files.")
    parser.add_argument("--clean", action="store_true",
                        help="Remove existing preset output before rebuilding.")
    args = parser.parse_args()

    if not STOCK_LUA.exists():
        print(f"error: stock file missing: {STOCK_LUA}", file=sys.stderr)
        print("       extract it with `relic sga unpack` from <game>/Engine/Engine.sga",
              file=sys.stderr)
        return 1

    # Read with default text mode (universal newlines) for parsing, but remember
    # the original line ending so we can preserve it when writing.
    stock_bytes = STOCK_LUA.read_bytes()
    stock_text = stock_bytes.decode("utf-8")
    # If the source uses CRLF, normalise to LF for parsing then re-CRLF on write
    # by injecting CR back before every LF that originally had one.
    # Simpler: keep text as-is — splitlines(keepends=True) preserves CRLF.

    if args.clean and PRESETS_DIR.exists() and not args.dry_run:
        shutil.rmtree(PRESETS_DIR)

    print(f"▶ Generating presets from {STOCK_LUA.relative_to(REPO_ROOT)}")
    print(f"  bindings_version: "
          f"{re.search(r'bindings_version\s*=\s*([0-9.]+)', stock_text).group(1)}")

    print("• vanilla")
    write_preset("vanilla", stock_text, stock_text, args.dry_run)

    print("• wasd-camera")
    wasd_text = build_wasd(stock_text)
    diff_count = sum(1 for a, b in zip(stock_text.splitlines(), wasd_text.splitlines())
                     if a != b)
    print(f"  transformed {diff_count} lines")
    write_preset("wasd-camera", wasd_text, stock_text, args.dry_run)

    print("• wasd-camera-ingame")
    ingame_text = retarget_ingame(wasd_text)
    print(f"  filename: keydefaults_modern.lua (overrides Modern slot)")
    print(f"  bindings_locstring: {INGAME_LOCSTRING!r} (= 'Modern Hotkeys')")
    write_preset("wasd-camera-ingame", ingame_text, stock_text, args.dry_run,
                 deploy_path=INGAME_DEPLOY_PATH)

    print("✓ done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
