#!/usr/bin/env python3
"""
lint.py — Enforce WH40K zh-TW terminology in translation files.

Exits with code 1 if any violations are found (suitable for CI).

Usage:
    python3 tools/scripts/lint.py [--strict]
"""

import argparse
import csv
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TRANSLATION_DIR = REPO_ROOT / "translation" / "zh-TW" / "Text"
GLOSSARY_PATH = REPO_ROOT / "glossary" / "wh40k-tc-glossary.csv"


_SEP = re.compile(r'(?<!\\)=')


def load_entries(directory: Path) -> list[tuple[Path, int, str, str]]:
    """Return (file, lineno, key, value) for every translation entry.
    The separator is the first '=' NOT preceded by a backslash.
    """
    results = []
    for txt in sorted(directory.glob("*.txt")):
        if txt.name.startswith("_Auto"):
            continue  # skip baseline auto-gen; only lint manual files
        with open(txt, encoding="utf-8", errors="replace") as f:
            for lineno, line in enumerate(f, 1):
                line = line.rstrip("\n")
                if not line or line.startswith("//"):
                    continue
                m = _SEP.search(line)
                if not m:
                    continue
                results.append((txt, lineno, line[:m.start()], line[m.end():]))
    return results


def load_glossary() -> list[dict]:
    with open(GLOSSARY_PATH, encoding="utf-8") as f:
        return list(csv.DictReader(f))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true",
                        help="Also lint _AutoGeneratedTranslations.txt")
    args = parser.parse_args()

    entries = load_entries(TRANSLATION_DIR)
    if args.strict:
        # Also include the auto-gen baseline
        for txt in sorted(TRANSLATION_DIR.glob("_Auto*.txt")):
            with open(txt, encoding="utf-8", errors="replace") as f:
                for lineno, line in enumerate(f, 1):
                    line = line.rstrip("\n")
                    if not line or line.startswith("//"):
                        continue
                    idx = line.find("=")
                    if idx == -1:
                        continue
                    entries.append((txt, lineno, line[:idx], line[idx + 1:]))

    glossary = load_glossary()
    errors: list[str] = []

    for row in glossary:
        sc = row["sc_term"]
        tc_expected = row["tc_term"]
        if sc == tc_expected:
            continue  # identical — nothing to enforce
        for fpath, lineno, key, val in entries:
            if sc in val and tc_expected not in val:
                errors.append(
                    f"{fpath.name}:{lineno}: SC term '{sc}' found in TC value "
                    f"(expected '{tc_expected}')\n  → {val[:100]}"
                )

    if errors:
        print(f"lint: {len(errors)} terminology violation(s) found\n", file=sys.stderr)
        for e in errors:
            print(e, file=sys.stderr)
        sys.exit(1)
    else:
        print("lint: OK — no terminology violations.")


if __name__ == "__main__":
    main()
